const BASE_PROTOCOL = process.env.SA_PROTOCOL;
const BASE_HOST = process.env.SA_HOST;
const WEBSOCKET_PROTOCOL = (BASE_PROTOCOL === 'https') ? 'wss' : 'ws';
const BASE_URL = `${BASE_PROTOCOL}://${BASE_HOST}/`;
const BASE_API_URL = `${BASE_URL}api/v0/`;

const AUTH_API_URL = `${BASE_API_URL}auth/`;
const USERS_API_URL = `${BASE_API_URL}users/`;
const DONATIONS_API_URL = `${BASE_API_URL}donations/`;
const AUDIO_API_URL = `${BASE_API_URL}audio/`;
const NEWS_API_URL = `${BASE_API_URL}news/`;
const SETTINGS_API_URL = `${BASE_API_URL}user_settings/`;
const MEDIA_API_URL = `${BASE_API_URL}user_media/`;
const DONATION_GOAL_API_URL = `${BASE_API_URL}donation_goals/`;

const TWITCH_API_BASE_URL = 'https://api.twitch.tv/kraken/';

const SORTING_ORDER = {
  ACS: 'asc',
  DESC: 'desc'
};

const SETTINGS_CATEGORY = {
  GENERAL: 'general',
  PAYMENTS: 'payments',
  DONATION_PAGE: 'donation'
};

const WIDGETS_CATEGORY = {
  ALERTS: 'alerts',
  DONATION_GOAL: 'donation-goal'
};

const TTS_STATUS = {
  ENABLED: 'on',
  DISABLED: 'off'
};

const TTS_VOICE = {
  MAXIM: 'MAXIM',
  TATYANA: 'TATYANA',
  ALEKSANDR: 'ALEKSANDR'
};

const NOTIFY_TWITCH_CHAT_DONATIONS = {
  YES: 'yes',
  NO: 'no'
};

const READ_DONATION_META = {
  YES: 'yes',
  NO: 'no'
};

const NONE_OPTION = 'None';
const PROMISE_OK = 'ok';

const DONATION_TITLE_SENDER_TEMPLATE = '{sender}';
const DONATION_TITLE_AMOUNT_TEMPLATE = '{amount}';

const MEDIA_TYPE = {
  DONATION_SOUND: 'donationSound',
  DONATION_IMAGE: 'donationImage'
};

const DONATION_TYPE = {
  MANUAL: 'MANUAL',
  WEBMONEY: 'WEBMONEY',
  YANDEX_WALLET: 'YANDEX_WALLET',
  YANDEX_CREDIT_CARD: 'YANDEX_CREDIT_CARD',
  UNITPAY: 'UNITPAY',
  UNITPAY_MC: 'UNITPAY_MC',
  UNITPAY_MC_MTS: 'UNITPAY_MC_MTS',
  UNITPAY_MC_MEGAFON: 'UNITPAY_MC_MEGAFON',
  UNITPAY_MC_BEELINE: 'UNITPAY_MC_BEELINE',
  UNITPAY_MC_TELE2: 'UNITPAY_MC_TELE2',
  UNITPAY_SMS: 'UNITPAY_SMS',
  UNITPAY_CARD: 'UNITPAY_CARD',
  UNITPAY_WEBMONEY: 'UNITPAY_WEBMONEY',
  UNITPAY_YANDEX: 'UNITPAY_YANDEX',
  UNITPAY_QIWI: 'UNITPAY_QIWI',
  UNITPAY_ALFACLICK: 'UNITPAY_ALFACLICK',
  UNITPAY_CASH: 'UNITPAY_CASH'
};

const INPUT_NO_VALUE = '';

const ACCOUNT_TYPE = {
  TWITCH: 'TWITCH'
};

const HOWTO_PATHS = {
  VIEWER: 'viewer',
  STREAMER: 'streamer'
};

const DONATION_SIGNATURE = {
  NONE: 'NONE',
  TWITCH: 'TWITCH'
};

const Constants = {
  TWITCH_URL: 'http://twitch.tv',
  BASE_URL: BASE_URL,

  VK_GROUP_LINK: 'https://vk.com/4streamgroup',
  VK_PROMO_DISCUSSION_LINK: 'https://vk.com/topic-126502081_34169270',
  TWITTER_LINK: 'https://twitter.com/_4stream',

  TWITCH_APP_ID: process.env.TWITCH_APP_ID,
  WEBSOCKET_DONATION_URL: `${WEBSOCKET_PROTOCOL}://${BASE_HOST}/donations_ws`,
  TWITCH_AUTH_PERMISSIONS: 'user_read',
  TWITCH_STATE_DASHBOARD_LOGIN: 'dashboard_login',
  TWITCH_STATE_SENDER_LOGIN: 'sender_login',
  STREAM_ASSIST_TWITCH_LOGIN: '4_stream',
  STREAM_ASSIST_WEB_MONEY_WALLET: 'R581937458226',
  STREAM_ASSIST_WEB_MONEY_ID: '467496827619',
  STREAM_ASSIST_YANDEX_WALLET: '410014323344477',

  UNIT_PAY_SHOP_ID: '56741-f9266',
  
  SUPPORT_MAIL: 'support@4stream.ru',
  
  DONATION_PAGE_URL: '/donate',
  DONATION_PAGE_URL_FULL: `${BASE_URL}donate`,
  DONATION_WIDGET_URL: `/alert-widget`,
  DONATION_WIDGET_URL_FULL: `${BASE_URL}alert-widget`,
  DONATION_GOAL_URL: `/donation-goal`,
  DONATION_GOAL_URL_FULL: `${BASE_URL}donation-goal`,

  AUTH_API_URL_LOGIN: `${AUTH_API_URL}login`,
  AUTH_API_URL_LOGOUT: `${AUTH_API_URL}logout`,

  USER_API_URL_CURRENT: `${USERS_API_URL}current`,
  USER_API_URL_INFO: `${USERS_API_URL}user/twitch/`,
  USER_API_URL_PROMO: `${USERS_API_URL}promo_users`,
  USER_API_URL_RESET_TOKEN: `${USERS_API_URL}user_token`,

  DONATION_API_URL_SEND: `${DONATIONS_API_URL}donation`,
  DONATION_API_URL_SEND_TEST: `${DONATIONS_API_URL}donation_test`,
  DONATION_API_URL_PREPARE: `${DONATIONS_API_URL}prepare`,
  DONATION_API_URL_PREPARED_DONATION: `${DONATIONS_API_URL}prepared_donation/`,
  DONATION_API_URL_DELETE: `${DONATIONS_API_URL}donation/`,
  DONATION_API_URL_STATISTICS: `${DONATIONS_API_URL}statistics`,
  DONATION_API_URL_DONATIONS: `${DONATIONS_API_URL}donations`,

  AUDIO_API_URL_DONATION_SPEECH: `${AUDIO_API_URL}donation/`,
  AUDIO_API_URL_TTS_PREVIEW: `${AUDIO_API_URL}preview_tts`,
  AUDIO_API_URL_TEST_VOICE: `${AUDIO_API_URL}test_voice`,

  NEWS_API_URL_LATEST: `${NEWS_API_URL}latest_news`,

  SETTINGS_API_URL_USER_SETTINGS: `${SETTINGS_API_URL}user_settings`,
  SETTINGS_API_URL_DONATION_ALERT_SETTINGS: `${SETTINGS_API_URL}donation_alert_settings`,
  SETTINGS_API_URL_DONATION_ALERT_SETTINGS_BY_TOKEN: `${SETTINGS_API_URL}donation_alert_settings_by_token`,

  MEDIA_API_URL_DONATION_META: `${MEDIA_API_URL}meta`,
  MEDIA_API_URL_DONATION_SOUND: `${MEDIA_API_URL}donation_sound`,
  MEDIA_API_URL_DONATION_IMAGE: `${MEDIA_API_URL}donation_image`,

  DONATION_GOAL_API_URL_SETTINGS: `${DONATION_GOAL_API_URL}settings`,
  DONATION_GOAL_API_URL_DONATION_GOALS: `${DONATION_GOAL_API_URL}donation_goals`,
  DONATION_GOAL_API_URL_DONATION_GOAL: `${DONATION_GOAL_API_URL}donation_goal`,
  DONATION_GOAL_API_URL_WIDGET_DATA: `${DONATION_GOAL_API_URL}widget_data`,

  TWITCH_API_CHANNELS: `${TWITCH_API_BASE_URL}channels/`,
  TWITCH_API_STREAMS: `${TWITCH_API_BASE_URL}streams/`,
  TWITCH_DEFAULT_USER_LOGO_URL: '/resources/images/twitch_default_logo.png',

  DONATION_PROCESSING_INTERVAL_SEC: 1,
  DONATION_DISAPPEAR_DELAY_SEC: 3,
  DONATION_DISAPPEAR_ON_ERROR_DELAY_SEC: 7,
  
  DEFAULT_MIN_DONATION_AMOUNT: 3,
  DEFAULT_MIN_AMOUNT_FOR_SYNTHESIS: 3,
  MAX_DONATION_AMOUNT: 15000,
  MIN_VOLUME: 0,
  MAX_VOLUME: 100,
  DEFAULT_VOLUME: 100,

  DEFAULT_FONT: 'Ubuntu',
  DONATION_TITLE_DEFAULT_FONT_SIZE: 36,
  DONATION_TITLE_DEFAULT_FONT_COLOR: '#3498db',
  DONATION_TITLE_DEFAULT_SHADOW_SIZE: 1,
  DONATION_TITLE_DEFAULT_SHADOW_COLOR: '#000000',
  DONATION_TITLE_DEFAULT_BACKGROUND_COLOR: '#000000',
  DONATION_TITLE_DEFAULT_BACKGROUND_OPACITY: 0,

  DONATION_TEXT_DEFAULT_FONT_SIZE: 24,
  DONATION_TEXT_DEFAULT_FONT_COLOR: '#FFFFFF',
  DONATION_TEXT_DEFAULT_SHADOW_SIZE: 1,
  DONATION_TEXT_DEFAULT_SHADOW_COLOR: '#000000',
  DONATION_TEXT_DEFAULT_BACKGROUND_COLOR: '#000000',
  DONATION_TEXT_DEFAULT_BACKGROUND_OPACITY: 50,

  DONATION_GOAL_DEFAULT_TEXT_FONT_SIZE: 24,
  DONATION_GOAL_DEFAULT_BAR_TEXT_FONT_SIZE: 28,
  DONATION_GOAL_DEFAULT_SHADOW_SIZE: 1,
  DONATION_GOAL_DEFAULT_SHADOW_COLOR: '#000000',
  DONATION_GOAL_DEFAULT_BACKGROUND_COLOR: '#000000',
  DONATION_GOAL_DEFAULT_BACKGROUND_OPACITY: 0,
  
  DONATION_GOAL_DEFAULT_TEXT_COLOR: '#00FF2D',
  DONATION_GOAL_DEFAULT_BAR_COLOR: '#0069FF',
  DONATION_GOAL_DEFAULT_BAR_TEXT_COLOR: '#00FF2D',
  DONATION_GOAL_DEFAULT_BAR_BACKGROUND_COLOR: '#7AA8BD',
  DONATION_GOAL_DEFAULT_BAR_THICKNESS: 50,
  DONATION_GOAL_MAX_TITLE_LENGTH: 50,
  DONATION_GOAL_MIN_AMOUNT: 1,
  DONATION_GOAL_MAX_AMOUNT: 999999,
  DONATION_GOALS_LIMIT: 5,
  MIN_BAR_THICKNESS: 30,
  MAX_BAR_THICKNESS: 100,

  DONATION_TITLE_SENDER_TEMPLATE: DONATION_TITLE_SENDER_TEMPLATE,
  DONATION_TITLE_AMOUNT_TEMPLATE: DONATION_TITLE_AMOUNT_TEMPLATE,
  DONATION_TITLE_TEMPLATE_DEFAULT: `${DONATION_TITLE_SENDER_TEMPLATE} - ${DONATION_TITLE_AMOUNT_TEMPLATE}`,
  DONATION_TITLE_TEMPLATE_MAX_LENGTH: 35,
  DONATION_SENDER_TWITCH_PLACEHOLDER: '\uFFFF',

  DONATION_SENDER_MAX_LENGTH: 25,
  
  MAX_UPLOAD_SIZE_MB: 4,
  MAX_DONATION_CHARACTERS: 300,
  MAX_DONATION_PAGE_TEXT_LENGTH: 200,
  
  COOKIE_REDIRECT: 'redirectUrl',
  COOKIE_MESSAGE_ID: 'messageId',
  COOKIE_SAVED_DONATION: 'savedDonation',
  COOKIE_WELCOME_DIALOG: 'welcomeDialog',
  WELCOME_DIALOG_DISPLAYED: 'displayed',
  AUTH_ERROR_MESSAGE_ID: 'AUTH_ERROR',
  PAYMENT_SUCCESS_MESSAGE_ID: 'PAYMENT_SUCCESS',
  PAYMENT_ERROR_MESSAGE_ID: 'PAYMENT_ERROR',

  RUBLE: 'RUB',
  // payment description is supposed to be no longer than 50 symbols
  PAYMENT_DESCRIPTION: '4stream: donation to \'%s\'',
  
  // it's lower bound for payment from credit cards
  MIN_YANDEX_MONEY_AMOUNT: 1.02,

  WELCOME_DIALOG_EXPIRATION_MINUTES: 60 * 24,
  WELCOME_DIALOG_VIDEO_GUIDE_URL: 'https://www.youtube.com/watch?v=r_H8HLxA414',
  WELCOME_DIALOG_PROMO_PRESENTATION_URL: 'https://www.genial.ly/584938f2ed89647df8b8864e/4stream-promo',

  HTTP_HEADER_FILE_NAME: 'X-File-Name'
};
export default Constants;
export {SORTING_ORDER, WIDGETS_CATEGORY, SETTINGS_CATEGORY, TTS_STATUS, NONE_OPTION, MEDIA_TYPE, DONATION_TYPE, INPUT_NO_VALUE,
    ACCOUNT_TYPE, HOWTO_PATHS, PROMISE_OK, NOTIFY_TWITCH_CHAT_DONATIONS, READ_DONATION_META, DONATION_SIGNATURE, TTS_VOICE};
