import {DONATION_TYPE} from './Constants';

const FEE_CONSTANT_RECEIVE = 0.3;
const FEE_QIWI_WITHDRAW = 0.015;


const PAYMENT_TYPE = {
  [DONATION_TYPE.WEBMONEY]: 'PAYMENT_WEBMONEY',
  [DONATION_TYPE.YANDEX_WALLET]: 'PAYMENT_YANDEX_WALLET',
  [DONATION_TYPE.YANDEX_CREDIT_CARD]: 'PAYMENT_YANDEX_CREDIT_CARD',
  [DONATION_TYPE.UNITPAY_WEBMONEY]: 'PAYMENT_UNITPAY_WEBMONEY',
  [DONATION_TYPE.UNITPAY_QIWI]: 'PAYMENT_UNITPAY_QIWI',
  [DONATION_TYPE.UNITPAY_YANDEX]: 'PAYMENT_UNITPAY_YANDEX',
  [DONATION_TYPE.UNITPAY_CARD]: 'PAYMENT_UNITPAY_CARD',
  [DONATION_TYPE.UNITPAY_ALFACLICK]: 'PAYMENT_UNITPAY_ALFACLICK',
  [DONATION_TYPE.UNITPAY_MC_MTS]: 'PAYMENT_UNITPAY_UNITPAY_MC_MTS',
  [DONATION_TYPE.UNITPAY_MC_MEGAFON]: 'PAYMENT_UNITPAY_UNITPAY_MC_MEGAFON',
  [DONATION_TYPE.UNITPAY_MC_BEELINE]: 'PAYMENT_UNITPAY_UNITPAY_MC_BEELINE',
  [DONATION_TYPE.UNITPAY_MC_TELE2]: 'PAYMENT_UNITPAY_UNITPAY_MC_TELE_2'
};

const DIRECT_PAYMENTS = {
  [DONATION_TYPE.WEBMONEY]: 0.02,
  [DONATION_TYPE.YANDEX_WALLET]: 0.02,
  [DONATION_TYPE.YANDEX_CREDIT_CARD]: 0.035
};

// need to add 0.01 to each to include service fee
const UNITPAY_PAYMENTS = {
  [DONATION_TYPE.UNITPAY_WEBMONEY]: 0.025,
  [DONATION_TYPE.UNITPAY_QIWI]: 0.07,
  [DONATION_TYPE.UNITPAY_YANDEX]: 0.08,
  [DONATION_TYPE.UNITPAY_CARD]: 0.05,
  [DONATION_TYPE.UNITPAY_ALFACLICK]: 0.06,
  [DONATION_TYPE.UNITPAY_MC_MTS]: 0.15,
  [DONATION_TYPE.UNITPAY_MC_MEGAFON]: 0.19,
  [DONATION_TYPE.UNITPAY_MC_BEELINE]: 0.20,
  [DONATION_TYPE.UNITPAY_MC_TELE2]: 0.19
};

const WITHDRAW_FEE = {
  [DONATION_TYPE.UNITPAY_QIWI]: FEE_QIWI_WITHDRAW
};

function calculateAmountWithFee(paymentType, amount) {
  let result = 0.0;
  if (DIRECT_PAYMENTS.hasOwnProperty(paymentType)) {
    result = (amount * (1.0 - DIRECT_PAYMENTS[paymentType]) - FEE_CONSTANT_RECEIVE);
  } else {
    result = (amount * (1.0 - UNITPAY_PAYMENTS[paymentType]) - FEE_CONSTANT_RECEIVE);
    result = result * (1 - FEE_QIWI_WITHDRAW);
  }
  return result;
}

export {PAYMENT_TYPE, DIRECT_PAYMENTS, UNITPAY_PAYMENTS, FEE_CONSTANT_RECEIVE, WITHDRAW_FEE, calculateAmountWithFee};
